### PR TITLE
Fix includes

### PR DESCRIPTION
**Pull request by wsmckenz**
include has been deprecated in favor of includes.

### CODE REVIEW

**Comment by qiu8310** [comment]
`include` is an alias for `includes`, so this is no need

**Comment by wsmckenz** [comment]
Not any more. It's been removed.

Sent from my Mobile.
wsmckenz@cartewright.com

On Thu, Jul 7, 2016 at 9:27 PM -0500, "Zhonglei Qiu" notifications@github.com wrote:

include is an alias for includes, so this is no need

**Comment by qiu8310** [comment]
Sorry, I'm using a old version of lodash document in local. 
Merged, thanks!

**Comment by wsmckenz** [comment]
Thank you!

Sent from my Mobile.
wsmckenz@cartewright.com

On Fri, Jul 8, 2016 at 1:17 AM -0500, "Zhonglei Qiu" notifications@github.com wrote:

Sorry, I'm using a old version of lodash document in local. 

Merged, thanks!

**Pull request merged**
